src/Entity/Empresa.php
<?php

namespace App\Entity;

use App\Repository\EmpresaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EmpresaRepository::class)
 */
class Empresa
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=9)
     * @Assert\NotNull(message="El cif es obligatori")
     */
    private $cif;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\NotNull(message="El nom es obligatori")
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotNull(message="El telefon es obligatori")
     */
    private $telefon;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="El mail es obligatori")
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="La adreça es obligatoria")
     */
    private $adresa;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $hora_entrada;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $hora_eixida;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $alta = true;

    /**
     * @ORM\OneToMany(targetEntity=Representant::class, mappedBy="empresa")
     */
    private $representants;

    /**
     * @ORM\OneToMany(targetEntity=Practica::class, mappedBy="empresa")
     */
    private $practiques;

    public function __construct()
    {
        $this->representants = new ArrayCollection();
        $this->practiques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCif(): ?string
    {
        return $this->cif;
    }

    public function setCif(?string $cif): self
    {
        $this->cif = $cif;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelefon(): ?int
    {
        return $this->telefon;
    }

    public function setTelefon(?int $telefon): self
    {
        $this->telefon = $telefon;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getAdresa(): ?string
    {
        return $this->adresa;
    }

    public function setAdresa(?string $adresa): self
    {
        $this->adresa = $adresa;

        return $this;
    }

    public function getHoraEntrada(): ?\DateTimeInterface
    {
        return $this->hora_entrada;
    }

    public function setHoraEntrada(?\DateTimeInterface $hora_entrada): self
    {
        $this->hora_entrada = $hora_entrada;

        return $this;
    }

    public function getHoraEixida(): ?\DateTimeInterface
    {
        return $this->hora_eixida;
    }

    public function setHoraEixida(?\DateTimeInterface $hora_eixida): self
    {
        $this->hora_eixida = $hora_eixida;

        return $this;
    }

    public function getAlta(): ?bool
    {
        return $this->alta;
    }

    public function setAlta(?bool $alta): self
    {
        $this->alta = $alta;

        return $this;
    }

    /**
     * @return Collection|Representant[]
     */
    public function getRepresentants(): Collection
    {
        return $this->representants;
    }

    public function addRepresentant(Representant $representant): self
    {
        if (!$this->representants->contains($representant)) {
            $this->representants[] = $representant;
            $representant->setEmpresa($this);
        }

        return $this;
    }

    public function removeRepresentant(Representant $representant): self
    {
        if ($this->representants->removeElement($representant)) {
            // set the owning side to null (unless already changed)
            if ($representant->getEmpresa() === $this) {
                $representant->setEmpresa(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Practica[]
     */
    public function getPractiques(): Collection
    {
        return $this->practiques;
    }

    public function addPractique(Practica $practique): self
    {
        if (!$this->practiques->contains($practique)) {
            $this->practiques[] = $practique;
            $practique->setEmpresa($this);
        }

        return $this;
    }

    public function removePractique(Practica $practique): self
    {
        if ($this->practiques->removeElement($practique)) {
            // set the owning side to null (unless already changed)
            if ($practique->getEmpresa() === $this) {
                $practique->setEmpresa(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }
}

src/Form/EmpresaType.php
<?php

namespace App\Form;

use App\Entity\Empresa;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmpresaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cif')
            ->add('nom', TextType::class, [

                'label'=>'Nom',
                'required'=>true,
                'attr'=>[
                    'placeholder' => 'Nom',
                    'class'=>'form-control shadow-none'
                ],
            ])
            ->add('telefon', NumberType::class,
                [
                    'label'=>'Telefon',
                    'required'=>true,
                    'attr'=>[
                        'placeholder' => 'Telefon',
                        'class'=>'form-control shadow-none'
                    ],
                ])
            ->add('mail',EmailType::class,[

                'label'=>'Email',
                'required'=>true,
                'attr'=>[
                    'placeholder' => 'Email',
                    'class'=>'form-control shadow-none'
                ],

            ])
            ->add('adresa', TextType::class, [

                'label'=>'Adreça',
                'required'=>true,
                'attr'=>[
                    'placeholder' => 'Adreça',
                    'class'=>'form-control shadow-none'
                ],
            ])
            ->add('hora_entrada', TimeType::class,[

                'widget' => 'single_text'
            ])
            ->add('hora_eixida', TimeType::class,[

                'widget' => 'single_text'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Empresa::class,
        ]);
    }
}

src/Controller/EmpresaController.php
<?php

namespace App\Controller;

use App\Entity\Empresa;
use App\Entity\Professor;
use App\Form\EmpresaType;
use App\Repository\EmpresaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/empresa')]
class EmpresaController extends AbstractController
{
    #[Route('/', name: 'empresa_index', methods: ['GET'])]
    public function index(EmpresaRepository $empresaRepository): Response
    {
        return $this->render('empresa/index.html.twig', [
            'empresas' => $empresaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'empresa_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $empresa = new Empresa();
        $form = $this->createForm(EmpresaType::class, $empresa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($empresa);
            $entityManager->flush();

            return $this->redirectToRoute('empresa_index');
        }

        return $this->render('empresa/new.html.twig', [
            'empresa' => $empresa,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/show/{id}', name: 'empresa_show', methods: ['GET'])]
    public function show(Empresa $empresa): Response
    {
        return $this->render('empresa/show.html.twig', [
            'empresa' => $empresa,
        ]);
    }

    #[Route('/{id}/edit', name: 'empresa_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Empresa $empresa): Response
    {
        $form = $this->createForm(EmpresaType::class, $empresa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('empresa_index');
        }

        return $this->render('empresa/edit.html.twig', [
            'empresa' => $empresa,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'empresa_alta', methods: ['POST'])]
    public function alta(Request $request, Empresa $empresa): Response
    {
        if ($this->isCsrfTokenValid('delete'.$empresa->getId(), $request->request->get('_token'))) {

            $alta = $empresa->getAlta();
            if($alta == true){
                $empresa->setAlta(false);
            }else{
                $empresa->setAlta(true);
            }
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->redirectToRoute('empresa_index');
    }
    #[Route('/filter', name: 'empresa_filter', methods: ['GET'])]

    public function filter(Request $request)
    {
        $text = $request->query->getAlnum("text");
        $representantRepository = $this->getDoctrine()->getRepository(Empresa::class);
        $empreses = $representantRepository->filterByText($text);

        return $this->render('empresa/index.html.twig', array(
            'empresas' => $empreses
        ));

    }


}

templates/empresa/_delete_form.html.twig
{#<form method="post" action="{{ path('empresa_delete', {'id': empresa.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ empresa.id) }}">
    <button class="btn">Delete</button>
</form>#}

templates/empresa/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/empresa/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Empresa{% endblock %}

{% block body %}

    {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}


    <div class="row m-0 mt-3">


        <div class="col-8 mt-5">

            <div class="card shadow ">

                <div class="card-body">
                    <div class="contenedor bg-white">

                        <div class="row m-0">

                            <div class="col-12 ">
                                <small class="small-text">Formulari d'edició de empreses</small>
                            </div>
                        </div>

                        <div class="row m-0 ">
                            <div class="col-12 mt-2">

                                <h6>Informació bàsica de l'empresa</h6>
                                <hr>
                                <div class="form-group row m-0  mb-3">


                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.nom,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.nom) }}
                                            {#<input type="text"  class="form-control shadow-none" id="nom" value="" placeholder="Nom">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.nom) }}
                                </div>


                                <div class="form-group row m-0  mb-3">


                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.cif,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.cif) }}
                                            {#<input type="text"  class="form-control shadow-none" id="nom" value="" placeholder="Nom">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.cif) }}
                                </div>
                                <div class="form-group row m-0  mb-3">

                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.adresa,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.adresa) }}
                                            {#<input type="text"  class="form-control shadow-none" id="poblacio" value="" placeholder="Valencia">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.adresa) }}
                                </div>
                                <div class="form-group row m-0  mb-3">


                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.hora_entrada,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.hora_entrada) }}
                                            {#<input type="text"  class="form-control shadow-none" id="nom" value="" placeholder="Nom">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.hora_entrada) }}
                                </div>
                                <div class="form-group row m-0  mb-3">


                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.hora_eixida,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.hora_eixida) }}
                                            {#<input type="text"  class="form-control shadow-none" id="nom" value="" placeholder="Nom">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.hora_eixida) }}
                                </div>
                                <h6 class="mt-5">Informació de contacte</h6>
                                <hr>
                                <div class="form-group row m-0  mb-3">


                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.mail,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.mail) }}
                                            {#<input type="text"  class="form-control shadow-none" id="mail" value="" placeholder="example@gmail.com">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.mail) }}
                                </div>
                                <div class="form-group row m-0 mt-4 mb-3">

                                    <div class="col-sm-2 col-form-label bg-secondary text-white rounded-start">{{ form_label(form.telefon,null, {errors: []}) }}</div>
                                    <div class="col-10 p-0">
                                        <div class="input-group">

                                            {{ form_widget(form.telefon) }}
                                            {# <input type="text"  class="form-control shadow-none" id="tel" value="" placeholder="000000000">#}

                                        </div>
                                    </div>
                                    {{ form_errors(form.telefon) }}
                                </div>

                                <!-- <button type="submit" class="btn btn-primary">Submit</button> -->

                            </div>
                        </div>
                    </div>
                </div><!--fi card-body1-->

            </div>


        </div><!--fi columna principal-->

        <div class="col-4"></div>





    </div>

    <div class="row m-0">
        <div class="col-4 mt-2 ">

            <div class="card shadow h-100 containerBlue ">

                <button class="common-link color-heavyBlue btn w-100" type="submit" >
                    <div class="card-body">
                        <div class="contenedor">

                            <div class="h-100">

                                <div class="d-flex justify-content-center align-items-center"><i class="fa fa-check" aria-hidden="true"></i>
                                    &ensp; Validar les dades &ensp; </div>

                            </div>
                        </div>

                    </div><!--fi card-body1-->
                </button>
            </div>
        </div>
        <div class="col-4 mt-2  ">
            <div class="card shadow h-100 containerBlue">
                <button class="common-link color-heavyBlue btn w-100" type="submit" >
                    <div class="card-body">
                        <div class="contenedor">

                            <div class="h-100">

                                <div class="d-flex justify-content-center align-items-center"><i class="fa fa-pencil" aria-hidden="true"></i>
                                    &ensp; Editar &ensp; </div>

                            </div>
                        </div>

                    </div><!--fi card-body1-->
                </button>
            </div>
        </div>

    </div>



    {{ form_end(form) }}



{% endblock %}

templates/empresa/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Empreses{% endblock %}

{% block body %}
    <div class="row m-0 mt-5 ">

        <div class=" col-sm-2 col-md-2 col-lg-2 mt-3">

            <h3>Empreses</h3>
        </div>
        <div class="d-none d-sm-block col-sm-4 col-md-5 col-lg-5 mt-3">
            <form class="d-flex" method="get" action="{{ path('empresa_filter' ) }}">

                <div class="input-group">
                    <input type="text" name="text" class="form-control rounded shadow-none" placeholder="Cercar empresa" aria-label="Search"
                           aria-describedby="search-addon" />
                    <button type="submit" class="btn bg-turq shadow-none"><i class="fa fa-search text-light" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="d-none d-sm-block col-sm-3 col-md-3 col-lg-1 mt-3">
            <nav aria-label="">
                <ul class="pagination m-0">
                    <li class="page-item disabled">
                        <a class="page-link shadow-none" href="#" tabindex="-1" aria-disabled="true"><i class="fas fa-angle-left"></i></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link color-heavyBlue shadow-none" href="#"><i class="fas fa-angle-right"></i></a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="d-none d-sm-block col-sm-3 col-md-3 col-lg-3 mt-3">
        </div>
        <div class="col-sm-3 col-md-2 col-lg-1 mt-3">

            <a href="{{ path('empresa_new') }}" class="addNewlink">
                <div class="addNew">

                    <i class="fa fa-plus" aria-hidden="true"></i>
                </div>
            </a>

        </div>

    </div>
    <div class="row m-0 mt-2">
        <hr class="w-100">
    </div>

    <div class="row m-0 mt-3"> <!-- row empreses-->
    {% for empresa in empresas %}

        <div class="col-sm-12 col-md-6 col-lg-6 py-3 "> <!-- primer col 6-->

            <div class="card shadow ">


                <div class="card-body">
                    <div class="contenedor bg-white">

                        <div class="row m-0">

                            <div class="d-none d-md-block col-sm-2 col-md-2 col-lg-2 p-2 "><!--Contenedor foto-->

                                <div class="icon-photo">

                                    <i class="fa fa-university" aria-hidden="true"></i>
                                </div>


                            </div>
                            {% if empresa.alta == false %}

                                <div class="col-8 p-2"> <!--Contenedor text-->
                                    <div class="d-flex">
                                        <h5>{{ empresa.nom }}&ensp;</h5> <span><div class="text-danger"><i class="fa fa-circle" aria-hidden="true"></i> Inactiu </div></span>
                                    </div>
                                    <span> <h6 class="d-inline"> Horari de disponibilitat:</h6> {{ empresa.horaEntrada|date('H:i')  }} - {{ empresa.horaEixida|date('H:i') }} <br> {{ empresa.adresa }}. </span>
                                </div>

                            {% else %}
                                <div class="col-8 p-2"> <!--Contenedor text-->

                                    <div class="d-flex">
                                        <h5>{{ empresa.nom }} &ensp; </h5><span class="text-success"><i class="fa fa-circle" aria-hidden="true"></i> Actiu </span>
                                    </div>
                                    <span> <h6 class="d-inline"> Horari de disponibilitat:</h6> {{ empresa.horaEntrada|date('H:i')  }} - {{ empresa.horaEixida|date('H:i') }} <br> {{ empresa.adresa }}. </span>

                                </div>

                            {% endif %}


                            <div class="col-2 link-button "> <a href="{{ path('empresa_show', {'id': empresa.id}) }}"><button class="btn bg-turq shadow-none "><i class="fa fa-external-link shadow-none" aria-hidden="true"></i>
                                    </button></a></div><!--Contenedor link-->



                        </div>
                    </div>

                </div><!--fi card-body1-->
            </div>

        </div> <!-- fi primer col 6 -->
        {#        {% endif %}#}
    {% else %}
        </div>
        <div class="row m-0">

            <div class="col-12 py-3">

                <h5>No s'han trobat registres de empreses. <a href="{{ path('empresa_new') }}">Crear empresa</a></h5>
            </div>

        </div>

    {% endfor %}

{% endblock %}